import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, paddingTop: 50, paddingHorizontal: 20 },
  topHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  loadingText: {
    color: "#e74c3c",
    fontSize: 12,
    textAlign: "center",
    marginBottom: 10,
    fontWeight: "bold",
  },
  profileHeader: {
    alignItems: "center",
    paddingVertical: 24,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#3c3c3c",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: { fontSize: 35 },
  userInfo: { alignItems: "center", marginTop: 12 },
  welcomeText: { fontSize: 18, color: "#ffffff" },
  userName: { fontWeight: "bold", color: "#3498db", fontSize: 20 },
  changeNameButton: {
    backgroundColor: "#4a4a4a",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    marginTop: 12,
    alignSelf: "center",
  },
  changeNameButtonText: { color: "#e0e0e0", fontSize: 12, fontWeight: "600" },
  divider: { height: 1, backgroundColor: "#3c3c3c", marginVertical: 10 },
  menuContainer: {
    marginTop: 20,
    backgroundColor: "#262626",
    borderRadius: 12,
    paddingHorizontal: 15,
  },
  menuItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: "#3c3c3c",
  },
  menuText: { fontSize: 15, color: "#e5e5e5" },
  arrow: { fontSize: 14, color: "#555555" },
  securityFooter: {
    textAlign: "center",
    color: "#555555",
    fontSize: 11,
    marginTop: 40,
    marginBottom: 100,
  },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    backgroundColor: "#1A1A1A",
    paddingVertical: 15,
    justifyContent: "space-around",
    borderTopWidth: 1,
    borderTopColor: "#333",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "80%",
    backgroundColor: "#2c2c2c",
    borderRadius: 15,
    padding: 20,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 15,
  },
  modalInput: {
    width: "100%",
    backgroundColor: "#1c1c1c",
    color: "#fff",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#4a4a4a",
    marginBottom: 15, // 인풋 여러개일때 간격 조절을 위해 살짝 줄임
  },
  modalButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 5,
  },
  modalCancelButton: {
    flex: 1,
    backgroundColor: "#4a4a4a",
    padding: 12,
    borderRadius: 8,
    marginRight: 10,
    alignItems: "center",
  },
  modalCancelButtonText: { color: "#fff", fontWeight: "bold" },
  modalSaveButton: {
    flex: 1,
    backgroundColor: "#FF5252", // 앱 포인트 컬러인 붉은색으로 맞춤
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  modalSaveButtonText: { color: "#fff", fontWeight: "bold" },
});
