import { StyleSheet } from "react-native";

const C = {
  bg: "#0A0F1E",
  card: "#131B2E",
  card2: "#1A2540",
  border: "rgba(255,255,255,0.07)",
  green: "#00C896",
  greenDim: "rgba(0,200,150,0.12)",
  red: "#F87171",
  text: "#E2E8F0",
  sub: "#64748B",
  white: "#FFFFFF",
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },

  // ── 프로필 헤더 ──────────────────────────────
  profileHeader: {
    alignItems: "center",
    paddingTop: 70,
    paddingBottom: 28,
    paddingHorizontal: 20,
  },
  avatarWrapper: {
    position: "relative",
    marginBottom: 14,
  },
  avatar: {
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: C.card2,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: C.green,
  },
  avatarText: { fontSize: 38 },
  avatarBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: C.green,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: C.bg,
  },
  userName: {
    fontSize: 22,
    fontWeight: "800",
    color: C.text,
    marginBottom: 4,
  },
  userSubText: { fontSize: 14, color: C.sub, marginBottom: 16 },
  changeNameButton: {
    backgroundColor: C.card2,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: C.border,
  },
  changeNameButtonText: { color: C.sub, fontSize: 13, fontWeight: "600" },

  // ── 통계 카드 행 ──────────────────────────────
  statsRow: {
    flexDirection: "row",
    gap: 10,
    marginHorizontal: 16,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    backgroundColor: C.card,
    borderRadius: 16,
    padding: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: C.border,
  },
  statIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  statValue: { fontSize: 18, fontWeight: "800", color: C.text, marginBottom: 2 },
  statLabel: { fontSize: 11, color: C.sub },

  // ── 메뉴 그룹 ──────────────────────────────────
  menuSection: { marginHorizontal: 16, marginBottom: 12 },
  menuSectionLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: C.sub,
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  menuCard: {
    backgroundColor: C.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.border,
    overflow: "hidden",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    gap: 12,
  },
  menuItemLast: {
    borderBottomWidth: 0,
  },
  menuIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  menuText: { flex: 1, fontSize: 15, color: C.text, fontWeight: "500" },
  menuTextRed: { flex: 1, fontSize: 15, color: C.red, fontWeight: "500" },
  menuArrow: { opacity: 0.4 },

  // ── 하단 ──────────────────────────────────────
  footer: { height: 100 },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    backgroundColor: C.card,
    paddingBottom: 24,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: C.border,
  },
  navItem: { flex: 1, alignItems: "center", gap: 3 },
  navActiveIndicator: {
    position: "absolute",
    top: -10,
    width: 24,
    height: 3,
    backgroundColor: C.green,
    borderRadius: 2,
  },
  navLabel: { fontSize: 11, color: C.sub },
  navLabelActive: { fontSize: 11, color: C.green, fontWeight: "600" },

  // ── 모달 ──────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  modalContent: {
    width: "100%",
    backgroundColor: "#111827",
    borderRadius: 20,
    padding: 24,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: C.text,
    marginBottom: 16,
    textAlign: "center",
  },
  modalInput: {
    backgroundColor: C.card,
    color: C.text,
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    borderWidth: 1,
    borderColor: C.border,
    marginBottom: 12,
  },
  deleteWarningText: {
    color: C.sub,
    fontSize: 14,
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 22,
  },
  modalButtonContainer: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  modalCancelButton: {
    flex: 1,
    backgroundColor: C.card2,
    padding: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  modalCancelButtonText: { color: C.sub, fontWeight: "600" },
  modalSaveButton: {
    flex: 1,
    backgroundColor: C.green,
    padding: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  modalDeleteButton: {
    flex: 1,
    backgroundColor: "#7F1D1D",
    padding: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  modalSaveButtonText: { color: C.white, fontWeight: "700" },

  // legacy (호환)
  topHeader: {},
  loadingText: {},
  userInfo: {},
  welcomeText: {},
  divider: {},
  menuContainer: {},
  securityFooter: {},
  arrow: {},
});
