spring:
  datasource:
    url: jdbc:postgresql://dpg-d8nkl64m0tmc73e83r60-a/limitless_db
    username: limitless_db_user
    password: lq33O5rrnCbbrRxIwcXHPVPMiOc4CgJC
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000