server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://dpg-d8nkl64m0tmc73e83r60-a/limitless_db
    username: limitless_db_user
    password: lq33O5rrnCbbrRxIwcXHPVPMiOc4CgJC
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: https://limitless-project.onrender.com/login/oauth2/code/google

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

groq:
  api-key: ${GROQ_API_KEY:}
